
# External Modem Control Core
obj-$(CONFIG_EXMDM_CLASS)		+= exmdm-class.o

# External Modem Control Drivers
obj-$(CONFIG_EXMDM_STE_U300)		    += exmdms-steu300.o
obj-$(CONFIG_EXMDM_HUAWEI_820U)			+= exmdms-hw820u.o
obj-$(CONFIG_EXMDM_SIERRA_8705)			+= exmdms-sierra8705.o
